### ISSUE TITLE
websockify.js : Server disconnected (code: 1006) 

### ISSUE THREAD

**Issue by jude90** [novnc/websockify-js#3]
node : v.6.11.5 
webscokify@0.7.1
#websockify crashed when I conneccted at vnc.html 
trace back stack : 
```
/home/vagrant/node_modules/websockify/websockify.js:129
        callback(true, 'binary');
        ^

TypeError: callback is not a function
    at Object.selectProtocol [as handleProtocols] (/home/vagrant/node_modules/websockify/websockify.js:129:9)
    at WebSocketServer.handleUpgrade (/home/vagrant/node_modules/ws/lib/WebSocketServer.js:169:31)
    at Server.WebSocketServer._ultron.on (/home/vagrant/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)
    at Socket.socketOnData (_http_server.js:371:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
updated:
full dependency as follows 
└─┬ websockify@0.7.1
  ├─┬ optimist@0.6.1
  │ ├── minimist@0.0.10
  │ └── wordwrap@0.0.3
  ├── policyfile@0.0.6
  └─┬ ws@3.2.0
    ├── async-limiter@1.0.0
    ├── safe-buffer@5.1.1
    └── ultron@1.1.0

**Comment by CendioOssman** [comment]
Ah, thanks. We'll have to update our dependencies then. Thanks for figuring it out.
